---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-java-web-app
  name: docker-java-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-java-web-app
  strategy: {}
  template:
    metadata:
      labels:
        app: docker-java-web-app
    spec:
      containers:
      - image: master-node:5000/docker-java-web-app:v1
        name: docker-java-web-app
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-java-web-app
  name: docker-java-web-app
spec:
  ports:
  - name: "8080"
    nodePort: 30306
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-java-web-app
  type: NodePort
status:
  loadBalancer: {}
