---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: docker-java-web-app
  name: java-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: java-web-app
    spec:
      containers:
      - image: slave-node1.md/neerajbharti2007/docker-java-web-app
        name: docker-java-web-app
        ports:
        - name: docker-java-web-app
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: docker-java-web-app
  name: docker-java-web-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: docker-java-web-app
